export const INPUT_NUMBER = 'INPUT_NUMBER'
export const PLUS = 'PLUS'
export const MINUS = 'MINUS'
export const TIMES = 'TIMES'
export const DEVIDED = 'DEVIDED'
export const CLEAR = 'CLEAR'
export const EQUAL = 'EQUAL'
